### ISSUE TITLE
Adabot actions are failing

### ISSUE THREAD

**Issue by jepler** [adafruit/adabot#181]
See https://github.com/adafruit/adabot/runs/989713183?check_suite_focus=true
```
Run python3 -u -m adabot.circuitpython_bundle
Adafruit_CircuitPython_Bundle
Everything is already released.
CircuitPython_Community_Bundle
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/adabot/adabot/adabot/circuitpython_bundle.py", line 379, in <module>
    new_release(bundle, bundle_path)
  File "/home/runner/work/adabot/adabot/adabot/circuitpython_bundle.py", line 317, in new_release
    commit_range)
  File "/home/runner/work/adabot/adabot/adabot/circuitpython_bundle.py", line 233, in get_contributors
    if github_commit_info["author"]:
KeyError: 'author'
##[error]Process completed with exit code 1.
```

@sommersoft speculates that this prevents only release of the community bundle, not the adafruit bundle.

**Comment by sommersoft** [comment]
The first occurrence of the error shows that the Adafruit bundle is successfully updated, while the error occurs on the Community bundle: https://github.com/adafruit/adabot/runs/969756000?check_suite_focus=true#step:8:1
```
Adafruit_CircuitPython_Bundle
Releasing 20200811
New libraries: [matrixportal](https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal/releases/1.0.0)
Updated libraries: [bitmapsaver](https://github.com/adafruit/Adafruit_CircuitPython_BitmapSaver/releases/1.1.2), [rsa](https://github.com/adafruit/Adafruit_CircuitPython_RSA/releases/1.2.0)

As always, thank you to all of our contributors: @makermelissa, @dherrada, @brentru, @***, @kattni, @FoamyGuy, @tannewt

--------------------------

The libraries in each release are compiled for all recent major versions of CircuitPython. Please download the one that matches the major version of your CircuitPython. For example, if you are running 4.0.0 you should download the `4.x` bundle.

To install, simply download the matching zip file, unzip it, and selectively copy the libraries you would like to install into the lib folder on your CIRCUITPY drive. This is especially important for non-express boards such as the [Trinket M0](https://www.adafruit.com/product/3500), [Gemma M0](https://www.adafruit.com/product/3501) and [Feather M0 Basic](https://www.adafruit.com/product/2772).
CircuitPython_Community_Bundle
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/adabot/adabot/adabot/circuitpython_bundle.py", line 379, in <module>
    new_release(bundle, bundle_path)
  File "/home/runner/work/adabot/adabot/adabot/circuitpython_bundle.py", line 317, in new_release
    commit_range)
  File "/home/runner/work/adabot/adabot/adabot/circuitpython_bundle.py", line 233, in get_contributors
    if github_commit_info["author"]:
KeyError: 'author'
##[error]Process completed with exit code 1.
```

Of the recent PR merges, none should be affecting this so it'll take some troubleshooting.

**Comment by sommersoft** [comment]
Looks like the cause is a [malformed URL](https://github.com/adafruit/CircuitPython_Community_Bundle/blob/7526a7f2be19fff31f0f7aa4fe5fe06f4cfb1be8/.gitmodules#L84) in the `.gitmodules` for the Community bundle:
```
(.env) ~/Dev/adabot/adabot:$> python -m adabot.circuitpython_bundle
CircuitPython_Community_Bundle
https://api.github.com/repos/Pimoroni_CircuitPython_LTR559//commits/03cba545e6d2a6079e2fe29b2f791818f65efe36
  repo: Pimoroni_CircuitPython_LTR559/
  error: KeyError: 'author' 
  api response: {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest'}
```
I'll get a PR in to fix the `.gitmodules` entry.

**Comment by jepler** [comment]
Confirmed success overnight: https://github.com/adafruit/adabot/actions/runs/211533728
