### ISSUE TITLE
Possible issue with adabot.arduino_libraries

### ISSUE THREAD

**Issue by dherrada** [adafruit/adabot#220]
I've checked this with the up-to-date version and an older version I had been using for a while to run the arduino library check. I get the same errors in both.

Output:
```
dherrada@dh:~/adafruit/adabot$ python3 -m adabot.arduino_libraries
Running Arduino Library Checks
Getting list of libraries to check...
Found 557 Arduino libraries to check

CRITICAL:root:Traceback (most recent call last):
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fb72910c790>, 'Connection to api.github.com timed out. (connect timeout=60)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/adafruit/Adafruit-MouseLogger/contents/examples (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb72910c790>, 'Connection to api.github.com timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dherrada/adafruit/adabot/adabot/github_requests.py", line 79, in request
    response = getattr(requests, method)(_fix_url(url), timeout=TIMEOUT, **_fix_kwargs(kwargs))
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/adafruit/Adafruit-MouseLogger/contents/examples (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb72910c790>, 'Connection to api.github.com timed out. (connect timeout=60)'))

Traceback (most recent call last):
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fb72910c790>, 'Connection to api.github.com timed out. (connect timeout=60)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/dherrada/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/adafruit/Adafruit-MouseLogger/contents/examples (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb72910c790>, 'Connection to api.github.com timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dherrada/adafruit/adabot/adabot/github_requests.py", line 79, in request
    response = getattr(requests, method)(_fix_url(url), timeout=TIMEOUT, **_fix_kwargs(kwargs))
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/dherrada/.local/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/adafruit/Adafruit-MouseLogger/contents/examples (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb72910c790>, 'Connection to api.github.com timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dherrada/adafruit/adabot/adabot/arduino_libraries.py", line 253, in <module>
    run_arduino_lib_checks()
  File "/home/dherrada/adafruit/adabot/adabot/arduino_libraries.py", line 181, in run_arduino_lib_checks
    have_examples = validate_example(repo)
  File "/home/dherrada/adafruit/adabot/adabot/arduino_libraries.py", line 165, in validate_example
    repo_has_ino = github.get("/repos/adafruit/" + repo["name"] + "/contents/examples")
  File "/home/dherrada/adafruit/adabot/adabot/github_requests.py", line 89, in request
    raise RuntimeError("See log for error text that has been sanitized for secrets")
RuntimeError: See log for error text that has been sanitized for secrets
```

**Comment by dherrada** [comment]
Just realized something else. The first time I ran it got hung up on Adafruit_CircuitPlayground_Android, the second time it got hung up on minipov4. These first two were with the out of date version. The third one, with the up to date version is requests library.

**Comment by dherrada** [comment]
Seems to have been fixed
