### ISSUE TITLE
Intermittent Travis cron Failures

### ISSUE THREAD

**Issue by sommersoft** [adafruit/adabot#59]
The cron jobs are having failures at a decent percentage. Luckily, the bundle updates are running smoothly, and the only issue seems to be in `circuitpython_libraries`. There are only two issues I see occurring:
1. Hitting the Travis 10 Minute Idle:
    - There is no output at all for these failures, which leads me to believe its related to the call for the latest `pylint` version.

2. Getting a `KeyError` exception:

```
Running CircuitPython library checks...
$ python -m adabot.circuitpython_libraries -o $LIB_CHECK_CP_FILE

Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/build/adafruit/adabot/adabot/circuitpython_libraries.py", line 1131, in <module>
    run_library_checks()
  File "/home/travis/build/adafruit/adabot/adabot/circuitpython_libraries.py", line 943, in run_library_checks
    errors = validate_repo(repo)
  File "/home/travis/build/adafruit/adabot/adabot/circuitpython_libraries.py", line 798, in validate_repo
    errors.extend(validator(repo))
  File "/home/travis/build/adafruit/adabot/adabot/circuitpython_libraries.py", line 297, in validate_repo_state
    full_repo = github.get("/repos/" + repo["full_name"])
  File "/home/travis/build/adafruit/adabot/adabot/github_requests.py", line 61, in get
    remaining = int(response.headers["X-RateLimit-Remaining"])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-ratelimit-remaining'
Latest pylint is: 2.2.2
Found 144 repos to check.
Found 129 submodules in the bundle.
Running GitHub checks as adafruit-adabot
Running Travis checks as adafruit-adabot
4900 requests remaining this hour
4800 requests remaining this hour
4700 requests remaining this hour
```

I'll try and replicate them, and figure out how to mitigate.

**Comment by sommersoft** [comment]
Reopening. Still hitting the Travis 10 minute idle limit for `circuitpython_libraries`. 🙁
